# Generated by Django 3.2.9 on 2021-11-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0002_auto_20211125_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='txout',
            name='txins',
            field=models.ManyToManyField(to='txouts.TxOut'),
        ),
    ]
