# Generated by Django 3.2.9 on 2021-11-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0004_auto_20211125_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txout',
            name='txins',
            field=models.ManyToManyField(null=True, to='txouts.TxOut'),
        ),
    ]
