# Generated by Django 3.2.9 on 2021-11-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0005_alter_txout_txins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txout',
            name='txins',
            field=models.ManyToManyField(blank=True, to='txouts.TxOut'),
        ),
    ]
