# Generated by Django 3.2.9 on 2021-11-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0007_auto_20211125_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='txout',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
