# Generated by Django 3.2.9 on 2021-11-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0008_auto_20211125_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='counterparty',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='txout',
            name='spent',
            field=models.BooleanField(default=False),
        ),
    ]
