# Generated by Django 3.2.9 on 2021-11-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0010_txout_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='txout',
            name='transaction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
