# Generated by Django 3.2.9 on 2021-12-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0011_txout_transaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='txout',
            unique_together={('address', 'transaction')},
        ),
    ]
