# Generated by Django 3.2.9 on 2021-12-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0014_txout_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='txout',
            name='spent_tx',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='txout',
            name='data',
            field=models.TextField(default='{}'),
        ),
    ]
