# Generated by Django 3.2.9 on 2021-12-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0015_auto_20211220_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txout',
            name='spent',
        ),
    ]
