# Generated by Django 3.2.9 on 2021-12-31 21:35

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0016_remove_txout_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='txout',
            name='encrypted_address',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='txout',
            name='encrypted_amount',
            field=encrypted_fields.fields.EncryptedBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='txout',
            name='encrypted_data',
            field=encrypted_fields.fields.EncryptedTextField(default='{}'),
        ),
        migrations.AddField(
            model_name='txout',
            name='encrypted_height',
            field=encrypted_fields.fields.EncryptedIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='txout',
            name='encrypted_notes',
            field=encrypted_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='txout',
            name='encrypted_spent_tx',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='txout',
            name='encrypted_transaction',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='txout',
            name='unique_key',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100),
        ),
    ]
