# Generated by Django 3.2.9 on 2022-01-02 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0019_alter_txout_unique_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='txout',
            unique_together=set(),
        ),
    ]
