# Generated by Django 3.2.9 on 2022-01-02 07:27

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('txouts', '0021_auto_20220102_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txout',
            name='encrypted_address',
        ),
        migrations.RemoveField(
            model_name='txout',
            name='encrypted_amount',
        ),
        migrations.RemoveField(
            model_name='txout',
            name='encrypted_data',
        ),
        migrations.RemoveField(
            model_name='txout',
            name='encrypted_height',
        ),
        migrations.RemoveField(
            model_name='txout',
            name='encrypted_notes',
        ),
        migrations.RemoveField(
            model_name='txout',
            name='encrypted_spent_tx',
        ),
        migrations.RemoveField(
            model_name='txout',
            name='encrypted_transaction',
        ),
        migrations.RemoveField(
            model_name='txout',
            name='txins',
        ),
        migrations.AlterField(
            model_name='txout',
            name='notes',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
    ]
